// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownloadLib.proto

#ifndef PROTOBUF_DownloadLib_2eproto__INCLUDED
#define PROTOBUF_DownloadLib_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "EReturnStatus.pb.h"
#include "msg-JK.pb.h"
// @@protoc_insertion_point(includes)

namespace transMsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DownloadLib_2eproto();
void protobuf_AssignDesc_DownloadLib_2eproto();
void protobuf_ShutdownFile_DownloadLib_2eproto();

class QDownloadLib;
class ADownloadLib;

// ===================================================================

class QDownloadLib : public ::google::protobuf::Message {
 public:
  QDownloadLib();
  virtual ~QDownloadLib();

  QDownloadLib(const QDownloadLib& from);

  inline QDownloadLib& operator=(const QDownloadLib& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QDownloadLib& default_instance();

  void Swap(QDownloadLib* other);

  // implements Message ----------------------------------------------

  QDownloadLib* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QDownloadLib& from);
  void MergeFrom(const QDownloadLib& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 VerCodes = 1 [packed = true];
  inline int vercodes_size() const;
  inline void clear_vercodes();
  static const int kVerCodesFieldNumber = 1;
  inline ::google::protobuf::int64 vercodes(int index) const;
  inline void set_vercodes(int index, ::google::protobuf::int64 value);
  inline void add_vercodes(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      vercodes() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_vercodes();

  // @@protoc_insertion_point(class_scope:transMsg.QDownloadLib)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > vercodes_;
  mutable int _vercodes_cached_byte_size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_DownloadLib_2eproto();
  friend void protobuf_AssignDesc_DownloadLib_2eproto();
  friend void protobuf_ShutdownFile_DownloadLib_2eproto();

  void InitAsDefaultInstance();
  static QDownloadLib* default_instance_;
};
// -------------------------------------------------------------------

class ADownloadLib : public ::google::protobuf::Message {
 public:
  ADownloadLib();
  virtual ~ADownloadLib();

  ADownloadLib(const ADownloadLib& from);

  inline ADownloadLib& operator=(const ADownloadLib& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ADownloadLib& default_instance();

  void Swap(ADownloadLib* other);

  // implements Message ----------------------------------------------

  ADownloadLib* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ADownloadLib& from);
  void MergeFrom(const ADownloadLib& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .transMsg.EReturnStatus Stats = 1;
  inline bool has_stats() const;
  inline void clear_stats();
  static const int kStatsFieldNumber = 1;
  inline ::transMsg::EReturnStatus stats() const;
  inline void set_stats(::transMsg::EReturnStatus value);

  // repeated int64 RejectedVerCodes = 3 [packed = true];
  inline int rejectedvercodes_size() const;
  inline void clear_rejectedvercodes();
  static const int kRejectedVerCodesFieldNumber = 3;
  inline ::google::protobuf::int64 rejectedvercodes(int index) const;
  inline void set_rejectedvercodes(int index, ::google::protobuf::int64 value);
  inline void add_rejectedvercodes(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      rejectedvercodes() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_rejectedvercodes();

  // repeated .transMsg.JK_Table JK_Table = 101;
  inline int jk_table_size() const;
  inline void clear_jk_table();
  static const int kJKTableFieldNumber = 101;
  inline const ::transMsg::JK_Table& jk_table(int index) const;
  inline ::transMsg::JK_Table* mutable_jk_table(int index);
  inline ::transMsg::JK_Table* add_jk_table();
  inline const ::google::protobuf::RepeatedPtrField< ::transMsg::JK_Table >&
      jk_table() const;
  inline ::google::protobuf::RepeatedPtrField< ::transMsg::JK_Table >*
      mutable_jk_table();

  // @@protoc_insertion_point(class_scope:transMsg.ADownloadLib)
 private:
  inline void set_has_stats();
  inline void clear_has_stats();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > rejectedvercodes_;
  mutable int _rejectedvercodes_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::transMsg::JK_Table > jk_table_;
  int stats_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_DownloadLib_2eproto();
  friend void protobuf_AssignDesc_DownloadLib_2eproto();
  friend void protobuf_ShutdownFile_DownloadLib_2eproto();

  void InitAsDefaultInstance();
  static ADownloadLib* default_instance_;
};
// ===================================================================


// ===================================================================

// QDownloadLib

// repeated int64 VerCodes = 1 [packed = true];
inline int QDownloadLib::vercodes_size() const {
  return vercodes_.size();
}
inline void QDownloadLib::clear_vercodes() {
  vercodes_.Clear();
}
inline ::google::protobuf::int64 QDownloadLib::vercodes(int index) const {
  return vercodes_.Get(index);
}
inline void QDownloadLib::set_vercodes(int index, ::google::protobuf::int64 value) {
  vercodes_.Set(index, value);
}
inline void QDownloadLib::add_vercodes(::google::protobuf::int64 value) {
  vercodes_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
QDownloadLib::vercodes() const {
  return vercodes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
QDownloadLib::mutable_vercodes() {
  return &vercodes_;
}

// -------------------------------------------------------------------

// ADownloadLib

// required .transMsg.EReturnStatus Stats = 1;
inline bool ADownloadLib::has_stats() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ADownloadLib::set_has_stats() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ADownloadLib::clear_has_stats() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ADownloadLib::clear_stats() {
  stats_ = 0;
  clear_has_stats();
}
inline ::transMsg::EReturnStatus ADownloadLib::stats() const {
  return static_cast< ::transMsg::EReturnStatus >(stats_);
}
inline void ADownloadLib::set_stats(::transMsg::EReturnStatus value) {
  assert(::transMsg::EReturnStatus_IsValid(value));
  set_has_stats();
  stats_ = value;
}

// repeated int64 RejectedVerCodes = 3 [packed = true];
inline int ADownloadLib::rejectedvercodes_size() const {
  return rejectedvercodes_.size();
}
inline void ADownloadLib::clear_rejectedvercodes() {
  rejectedvercodes_.Clear();
}
inline ::google::protobuf::int64 ADownloadLib::rejectedvercodes(int index) const {
  return rejectedvercodes_.Get(index);
}
inline void ADownloadLib::set_rejectedvercodes(int index, ::google::protobuf::int64 value) {
  rejectedvercodes_.Set(index, value);
}
inline void ADownloadLib::add_rejectedvercodes(::google::protobuf::int64 value) {
  rejectedvercodes_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ADownloadLib::rejectedvercodes() const {
  return rejectedvercodes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ADownloadLib::mutable_rejectedvercodes() {
  return &rejectedvercodes_;
}

// repeated .transMsg.JK_Table JK_Table = 101;
inline int ADownloadLib::jk_table_size() const {
  return jk_table_.size();
}
inline void ADownloadLib::clear_jk_table() {
  jk_table_.Clear();
}
inline const ::transMsg::JK_Table& ADownloadLib::jk_table(int index) const {
  return jk_table_.Get(index);
}
inline ::transMsg::JK_Table* ADownloadLib::mutable_jk_table(int index) {
  return jk_table_.Mutable(index);
}
inline ::transMsg::JK_Table* ADownloadLib::add_jk_table() {
  return jk_table_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::transMsg::JK_Table >&
ADownloadLib::jk_table() const {
  return jk_table_;
}
inline ::google::protobuf::RepeatedPtrField< ::transMsg::JK_Table >*
ADownloadLib::mutable_jk_table() {
  return &jk_table_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace transMsg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DownloadLib_2eproto__INCLUDED
