// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetLibStatus.proto

#ifndef PROTOBUF_GetLibStatus_2eproto__INCLUDED
#define PROTOBUF_GetLibStatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "EReturnStatus.pb.h"
#include "msg-GL.pb.h"
// @@protoc_insertion_point(includes)

namespace transMsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GetLibStatus_2eproto();
void protobuf_AssignDesc_GetLibStatus_2eproto();
void protobuf_ShutdownFile_GetLibStatus_2eproto();

class QGetLibStatus;
class AGetLibStatus;

// ===================================================================

class QGetLibStatus : public ::google::protobuf::Message {
 public:
  QGetLibStatus();
  virtual ~QGetLibStatus();

  QGetLibStatus(const QGetLibStatus& from);

  inline QGetLibStatus& operator=(const QGetLibStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QGetLibStatus& default_instance();

  void Swap(QGetLibStatus* other);

  // implements Message ----------------------------------------------

  QGetLibStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QGetLibStatus& from);
  void MergeFrom(const QGetLibStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 BeginTime = 11;
  inline bool has_begintime() const;
  inline void clear_begintime();
  static const int kBeginTimeFieldNumber = 11;
  inline ::google::protobuf::int64 begintime() const;
  inline void set_begintime(::google::protobuf::int64 value);

  // optional int64 EndTime = 12;
  inline bool has_endtime() const;
  inline void clear_endtime();
  static const int kEndTimeFieldNumber = 12;
  inline ::google::protobuf::int64 endtime() const;
  inline void set_endtime(::google::protobuf::int64 value);

  // repeated int64 VerCodes = 13 [packed = true];
  inline int vercodes_size() const;
  inline void clear_vercodes();
  static const int kVerCodesFieldNumber = 13;
  inline ::google::protobuf::int64 vercodes(int index) const;
  inline void set_vercodes(int index, ::google::protobuf::int64 value);
  inline void add_vercodes(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      vercodes() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_vercodes();

  // @@protoc_insertion_point(class_scope:transMsg.QGetLibStatus)
 private:
  inline void set_has_begintime();
  inline void clear_has_begintime();
  inline void set_has_endtime();
  inline void clear_has_endtime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 begintime_;
  ::google::protobuf::int64 endtime_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > vercodes_;
  mutable int _vercodes_cached_byte_size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_GetLibStatus_2eproto();
  friend void protobuf_AssignDesc_GetLibStatus_2eproto();
  friend void protobuf_ShutdownFile_GetLibStatus_2eproto();

  void InitAsDefaultInstance();
  static QGetLibStatus* default_instance_;
};
// -------------------------------------------------------------------

class AGetLibStatus : public ::google::protobuf::Message {
 public:
  AGetLibStatus();
  virtual ~AGetLibStatus();

  AGetLibStatus(const AGetLibStatus& from);

  inline AGetLibStatus& operator=(const AGetLibStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AGetLibStatus& default_instance();

  void Swap(AGetLibStatus* other);

  // implements Message ----------------------------------------------

  AGetLibStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AGetLibStatus& from);
  void MergeFrom(const AGetLibStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .transMsg.EReturnStatus Stats = 1;
  inline bool has_stats() const;
  inline void clear_stats();
  static const int kStatsFieldNumber = 1;
  inline ::transMsg::EReturnStatus stats() const;
  inline void set_stats(::transMsg::EReturnStatus value);

  // repeated .transMsg.GL_SugarVerInfo GL_SugarVerInfo = 101;
  inline int gl_sugarverinfo_size() const;
  inline void clear_gl_sugarverinfo();
  static const int kGLSugarVerInfoFieldNumber = 101;
  inline const ::transMsg::GL_SugarVerInfo& gl_sugarverinfo(int index) const;
  inline ::transMsg::GL_SugarVerInfo* mutable_gl_sugarverinfo(int index);
  inline ::transMsg::GL_SugarVerInfo* add_gl_sugarverinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::transMsg::GL_SugarVerInfo >&
      gl_sugarverinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::transMsg::GL_SugarVerInfo >*
      mutable_gl_sugarverinfo();

  // repeated string HashCodes = 102;
  inline int hashcodes_size() const;
  inline void clear_hashcodes();
  static const int kHashCodesFieldNumber = 102;
  inline const ::std::string& hashcodes(int index) const;
  inline ::std::string* mutable_hashcodes(int index);
  inline void set_hashcodes(int index, const ::std::string& value);
  inline void set_hashcodes(int index, const char* value);
  inline void set_hashcodes(int index, const char* value, size_t size);
  inline ::std::string* add_hashcodes();
  inline void add_hashcodes(const ::std::string& value);
  inline void add_hashcodes(const char* value);
  inline void add_hashcodes(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& hashcodes() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_hashcodes();

  // @@protoc_insertion_point(class_scope:transMsg.AGetLibStatus)
 private:
  inline void set_has_stats();
  inline void clear_has_stats();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::transMsg::GL_SugarVerInfo > gl_sugarverinfo_;
  ::google::protobuf::RepeatedPtrField< ::std::string> hashcodes_;
  int stats_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_GetLibStatus_2eproto();
  friend void protobuf_AssignDesc_GetLibStatus_2eproto();
  friend void protobuf_ShutdownFile_GetLibStatus_2eproto();

  void InitAsDefaultInstance();
  static AGetLibStatus* default_instance_;
};
// ===================================================================


// ===================================================================

// QGetLibStatus

// optional int64 BeginTime = 11;
inline bool QGetLibStatus::has_begintime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QGetLibStatus::set_has_begintime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QGetLibStatus::clear_has_begintime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QGetLibStatus::clear_begintime() {
  begintime_ = GOOGLE_LONGLONG(0);
  clear_has_begintime();
}
inline ::google::protobuf::int64 QGetLibStatus::begintime() const {
  return begintime_;
}
inline void QGetLibStatus::set_begintime(::google::protobuf::int64 value) {
  set_has_begintime();
  begintime_ = value;
}

// optional int64 EndTime = 12;
inline bool QGetLibStatus::has_endtime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void QGetLibStatus::set_has_endtime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void QGetLibStatus::clear_has_endtime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void QGetLibStatus::clear_endtime() {
  endtime_ = GOOGLE_LONGLONG(0);
  clear_has_endtime();
}
inline ::google::protobuf::int64 QGetLibStatus::endtime() const {
  return endtime_;
}
inline void QGetLibStatus::set_endtime(::google::protobuf::int64 value) {
  set_has_endtime();
  endtime_ = value;
}

// repeated int64 VerCodes = 13 [packed = true];
inline int QGetLibStatus::vercodes_size() const {
  return vercodes_.size();
}
inline void QGetLibStatus::clear_vercodes() {
  vercodes_.Clear();
}
inline ::google::protobuf::int64 QGetLibStatus::vercodes(int index) const {
  return vercodes_.Get(index);
}
inline void QGetLibStatus::set_vercodes(int index, ::google::protobuf::int64 value) {
  vercodes_.Set(index, value);
}
inline void QGetLibStatus::add_vercodes(::google::protobuf::int64 value) {
  vercodes_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
QGetLibStatus::vercodes() const {
  return vercodes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
QGetLibStatus::mutable_vercodes() {
  return &vercodes_;
}

// -------------------------------------------------------------------

// AGetLibStatus

// required .transMsg.EReturnStatus Stats = 1;
inline bool AGetLibStatus::has_stats() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AGetLibStatus::set_has_stats() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AGetLibStatus::clear_has_stats() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AGetLibStatus::clear_stats() {
  stats_ = 0;
  clear_has_stats();
}
inline ::transMsg::EReturnStatus AGetLibStatus::stats() const {
  return static_cast< ::transMsg::EReturnStatus >(stats_);
}
inline void AGetLibStatus::set_stats(::transMsg::EReturnStatus value) {
  assert(::transMsg::EReturnStatus_IsValid(value));
  set_has_stats();
  stats_ = value;
}

// repeated .transMsg.GL_SugarVerInfo GL_SugarVerInfo = 101;
inline int AGetLibStatus::gl_sugarverinfo_size() const {
  return gl_sugarverinfo_.size();
}
inline void AGetLibStatus::clear_gl_sugarverinfo() {
  gl_sugarverinfo_.Clear();
}
inline const ::transMsg::GL_SugarVerInfo& AGetLibStatus::gl_sugarverinfo(int index) const {
  return gl_sugarverinfo_.Get(index);
}
inline ::transMsg::GL_SugarVerInfo* AGetLibStatus::mutable_gl_sugarverinfo(int index) {
  return gl_sugarverinfo_.Mutable(index);
}
inline ::transMsg::GL_SugarVerInfo* AGetLibStatus::add_gl_sugarverinfo() {
  return gl_sugarverinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::transMsg::GL_SugarVerInfo >&
AGetLibStatus::gl_sugarverinfo() const {
  return gl_sugarverinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::transMsg::GL_SugarVerInfo >*
AGetLibStatus::mutable_gl_sugarverinfo() {
  return &gl_sugarverinfo_;
}

// repeated string HashCodes = 102;
inline int AGetLibStatus::hashcodes_size() const {
  return hashcodes_.size();
}
inline void AGetLibStatus::clear_hashcodes() {
  hashcodes_.Clear();
}
inline const ::std::string& AGetLibStatus::hashcodes(int index) const {
  return hashcodes_.Get(index);
}
inline ::std::string* AGetLibStatus::mutable_hashcodes(int index) {
  return hashcodes_.Mutable(index);
}
inline void AGetLibStatus::set_hashcodes(int index, const ::std::string& value) {
  hashcodes_.Mutable(index)->assign(value);
}
inline void AGetLibStatus::set_hashcodes(int index, const char* value) {
  hashcodes_.Mutable(index)->assign(value);
}
inline void AGetLibStatus::set_hashcodes(int index, const char* value, size_t size) {
  hashcodes_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AGetLibStatus::add_hashcodes() {
  return hashcodes_.Add();
}
inline void AGetLibStatus::add_hashcodes(const ::std::string& value) {
  hashcodes_.Add()->assign(value);
}
inline void AGetLibStatus::add_hashcodes(const char* value) {
  hashcodes_.Add()->assign(value);
}
inline void AGetLibStatus::add_hashcodes(const char* value, size_t size) {
  hashcodes_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
AGetLibStatus::hashcodes() const {
  return hashcodes_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
AGetLibStatus::mutable_hashcodes() {
  return &hashcodes_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace transMsg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GetLibStatus_2eproto__INCLUDED
