// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetOrderStatus.proto

#ifndef PROTOBUF_GetOrderStatus_2eproto__INCLUDED
#define PROTOBUF_GetOrderStatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "EReturnStatus.pb.h"
#include "EOrderState.pb.h"
// @@protoc_insertion_point(includes)

namespace transMsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GetOrderStatus_2eproto();
void protobuf_AssignDesc_GetOrderStatus_2eproto();
void protobuf_ShutdownFile_GetOrderStatus_2eproto();

class SOrderStatus;
class QGetOrderStatus;
class AGetOrderStatus;

// ===================================================================

class SOrderStatus : public ::google::protobuf::Message {
 public:
  SOrderStatus();
  virtual ~SOrderStatus();

  SOrderStatus(const SOrderStatus& from);

  inline SOrderStatus& operator=(const SOrderStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SOrderStatus& default_instance();

  void Swap(SOrderStatus* other);

  // implements Message ----------------------------------------------

  SOrderStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SOrderStatus& from);
  void MergeFrom(const SOrderStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 OrderID = 1;
  inline bool has_orderid() const;
  inline void clear_orderid();
  static const int kOrderIDFieldNumber = 1;
  inline ::google::protobuf::int64 orderid() const;
  inline void set_orderid(::google::protobuf::int64 value);

  // required .order.EOrderState OrderStatus = 2;
  inline bool has_orderstatus() const;
  inline void clear_orderstatus();
  static const int kOrderStatusFieldNumber = 2;
  inline ::order::EOrderState orderstatus() const;
  inline void set_orderstatus(::order::EOrderState value);

  // @@protoc_insertion_point(class_scope:transMsg.SOrderStatus)
 private:
  inline void set_has_orderid();
  inline void clear_has_orderid();
  inline void set_has_orderstatus();
  inline void clear_has_orderstatus();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 orderid_;
  int orderstatus_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_GetOrderStatus_2eproto();
  friend void protobuf_AssignDesc_GetOrderStatus_2eproto();
  friend void protobuf_ShutdownFile_GetOrderStatus_2eproto();

  void InitAsDefaultInstance();
  static SOrderStatus* default_instance_;
};
// -------------------------------------------------------------------

class QGetOrderStatus : public ::google::protobuf::Message {
 public:
  QGetOrderStatus();
  virtual ~QGetOrderStatus();

  QGetOrderStatus(const QGetOrderStatus& from);

  inline QGetOrderStatus& operator=(const QGetOrderStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QGetOrderStatus& default_instance();

  void Swap(QGetOrderStatus* other);

  // implements Message ----------------------------------------------

  QGetOrderStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QGetOrderStatus& from);
  void MergeFrom(const QGetOrderStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 OrderIDs = 1 [packed = true];
  inline int orderids_size() const;
  inline void clear_orderids();
  static const int kOrderIDsFieldNumber = 1;
  inline ::google::protobuf::int64 orderids(int index) const;
  inline void set_orderids(int index, ::google::protobuf::int64 value);
  inline void add_orderids(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      orderids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_orderids();

  // @@protoc_insertion_point(class_scope:transMsg.QGetOrderStatus)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > orderids_;
  mutable int _orderids_cached_byte_size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_GetOrderStatus_2eproto();
  friend void protobuf_AssignDesc_GetOrderStatus_2eproto();
  friend void protobuf_ShutdownFile_GetOrderStatus_2eproto();

  void InitAsDefaultInstance();
  static QGetOrderStatus* default_instance_;
};
// -------------------------------------------------------------------

class AGetOrderStatus : public ::google::protobuf::Message {
 public:
  AGetOrderStatus();
  virtual ~AGetOrderStatus();

  AGetOrderStatus(const AGetOrderStatus& from);

  inline AGetOrderStatus& operator=(const AGetOrderStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AGetOrderStatus& default_instance();

  void Swap(AGetOrderStatus* other);

  // implements Message ----------------------------------------------

  AGetOrderStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AGetOrderStatus& from);
  void MergeFrom(const AGetOrderStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .transMsg.EReturnStatus Stats = 1;
  inline bool has_stats() const;
  inline void clear_stats();
  static const int kStatsFieldNumber = 1;
  inline ::transMsg::EReturnStatus stats() const;
  inline void set_stats(::transMsg::EReturnStatus value);

  // repeated .transMsg.SOrderStatus OrderStatus = 2;
  inline int orderstatus_size() const;
  inline void clear_orderstatus();
  static const int kOrderStatusFieldNumber = 2;
  inline const ::transMsg::SOrderStatus& orderstatus(int index) const;
  inline ::transMsg::SOrderStatus* mutable_orderstatus(int index);
  inline ::transMsg::SOrderStatus* add_orderstatus();
  inline const ::google::protobuf::RepeatedPtrField< ::transMsg::SOrderStatus >&
      orderstatus() const;
  inline ::google::protobuf::RepeatedPtrField< ::transMsg::SOrderStatus >*
      mutable_orderstatus();

  // @@protoc_insertion_point(class_scope:transMsg.AGetOrderStatus)
 private:
  inline void set_has_stats();
  inline void clear_has_stats();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::transMsg::SOrderStatus > orderstatus_;
  int stats_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_GetOrderStatus_2eproto();
  friend void protobuf_AssignDesc_GetOrderStatus_2eproto();
  friend void protobuf_ShutdownFile_GetOrderStatus_2eproto();

  void InitAsDefaultInstance();
  static AGetOrderStatus* default_instance_;
};
// ===================================================================


// ===================================================================

// SOrderStatus

// required int64 OrderID = 1;
inline bool SOrderStatus::has_orderid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SOrderStatus::set_has_orderid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SOrderStatus::clear_has_orderid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SOrderStatus::clear_orderid() {
  orderid_ = GOOGLE_LONGLONG(0);
  clear_has_orderid();
}
inline ::google::protobuf::int64 SOrderStatus::orderid() const {
  return orderid_;
}
inline void SOrderStatus::set_orderid(::google::protobuf::int64 value) {
  set_has_orderid();
  orderid_ = value;
}

// required .order.EOrderState OrderStatus = 2;
inline bool SOrderStatus::has_orderstatus() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SOrderStatus::set_has_orderstatus() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SOrderStatus::clear_has_orderstatus() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SOrderStatus::clear_orderstatus() {
  orderstatus_ = 1;
  clear_has_orderstatus();
}
inline ::order::EOrderState SOrderStatus::orderstatus() const {
  return static_cast< ::order::EOrderState >(orderstatus_);
}
inline void SOrderStatus::set_orderstatus(::order::EOrderState value) {
  assert(::order::EOrderState_IsValid(value));
  set_has_orderstatus();
  orderstatus_ = value;
}

// -------------------------------------------------------------------

// QGetOrderStatus

// repeated int64 OrderIDs = 1 [packed = true];
inline int QGetOrderStatus::orderids_size() const {
  return orderids_.size();
}
inline void QGetOrderStatus::clear_orderids() {
  orderids_.Clear();
}
inline ::google::protobuf::int64 QGetOrderStatus::orderids(int index) const {
  return orderids_.Get(index);
}
inline void QGetOrderStatus::set_orderids(int index, ::google::protobuf::int64 value) {
  orderids_.Set(index, value);
}
inline void QGetOrderStatus::add_orderids(::google::protobuf::int64 value) {
  orderids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
QGetOrderStatus::orderids() const {
  return orderids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
QGetOrderStatus::mutable_orderids() {
  return &orderids_;
}

// -------------------------------------------------------------------

// AGetOrderStatus

// required .transMsg.EReturnStatus Stats = 1;
inline bool AGetOrderStatus::has_stats() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AGetOrderStatus::set_has_stats() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AGetOrderStatus::clear_has_stats() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AGetOrderStatus::clear_stats() {
  stats_ = 0;
  clear_has_stats();
}
inline ::transMsg::EReturnStatus AGetOrderStatus::stats() const {
  return static_cast< ::transMsg::EReturnStatus >(stats_);
}
inline void AGetOrderStatus::set_stats(::transMsg::EReturnStatus value) {
  assert(::transMsg::EReturnStatus_IsValid(value));
  set_has_stats();
  stats_ = value;
}

// repeated .transMsg.SOrderStatus OrderStatus = 2;
inline int AGetOrderStatus::orderstatus_size() const {
  return orderstatus_.size();
}
inline void AGetOrderStatus::clear_orderstatus() {
  orderstatus_.Clear();
}
inline const ::transMsg::SOrderStatus& AGetOrderStatus::orderstatus(int index) const {
  return orderstatus_.Get(index);
}
inline ::transMsg::SOrderStatus* AGetOrderStatus::mutable_orderstatus(int index) {
  return orderstatus_.Mutable(index);
}
inline ::transMsg::SOrderStatus* AGetOrderStatus::add_orderstatus() {
  return orderstatus_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::transMsg::SOrderStatus >&
AGetOrderStatus::orderstatus() const {
  return orderstatus_;
}
inline ::google::protobuf::RepeatedPtrField< ::transMsg::SOrderStatus >*
AGetOrderStatus::mutable_orderstatus() {
  return &orderstatus_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace transMsg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GetOrderStatus_2eproto__INCLUDED
