// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransferOrder.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TransferOrder.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace transMsg {

namespace {

const ::google::protobuf::Descriptor* QTransferOrder_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  QTransferOrder_reflection_ = NULL;
const ::google::protobuf::Descriptor* ATransferOrder_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ATransferOrder_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_TransferOrder_2eproto() {
  protobuf_AddDesc_TransferOrder_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TransferOrder.proto");
  GOOGLE_CHECK(file != NULL);
  QTransferOrder_descriptor_ = file->message_type(0);
  static const int QTransferOrder_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QTransferOrder, orderid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QTransferOrder, ownuser_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QTransferOrder, touser_),
  };
  QTransferOrder_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      QTransferOrder_descriptor_,
      QTransferOrder::default_instance_,
      QTransferOrder_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QTransferOrder, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QTransferOrder, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(QTransferOrder));
  ATransferOrder_descriptor_ = file->message_type(1);
  static const int ATransferOrder_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ATransferOrder, stats_),
  };
  ATransferOrder_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ATransferOrder_descriptor_,
      ATransferOrder::default_instance_,
      ATransferOrder_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ATransferOrder, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ATransferOrder, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ATransferOrder));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TransferOrder_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    QTransferOrder_descriptor_, &QTransferOrder::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ATransferOrder_descriptor_, &ATransferOrder::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_TransferOrder_2eproto() {
  delete QTransferOrder::default_instance_;
  delete QTransferOrder_reflection_;
  delete ATransferOrder::default_instance_;
  delete ATransferOrder_reflection_;
}

void protobuf_AddDesc_TransferOrder_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::transMsg::protobuf_AddDesc_EReturnStatus_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023TransferOrder.proto\022\010transMsg\032\023EReturn"
    "Status.proto\"B\n\016QTransferOrder\022\017\n\007OrderI"
    "D\030\001 \002(\003\022\017\n\007OwnUser\030\002 \002(\005\022\016\n\006ToUser\030\003 \002(\005"
    "\"8\n\016ATransferOrder\022&\n\005Stats\030\001 \002(\0162\027.tran"
    "sMsg.EReturnStatus", 178);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TransferOrder.proto", &protobuf_RegisterTypes);
  QTransferOrder::default_instance_ = new QTransferOrder();
  ATransferOrder::default_instance_ = new ATransferOrder();
  QTransferOrder::default_instance_->InitAsDefaultInstance();
  ATransferOrder::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TransferOrder_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TransferOrder_2eproto {
  StaticDescriptorInitializer_TransferOrder_2eproto() {
    protobuf_AddDesc_TransferOrder_2eproto();
  }
} static_descriptor_initializer_TransferOrder_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int QTransferOrder::kOrderIDFieldNumber;
const int QTransferOrder::kOwnUserFieldNumber;
const int QTransferOrder::kToUserFieldNumber;
#endif  // !_MSC_VER

QTransferOrder::QTransferOrder()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void QTransferOrder::InitAsDefaultInstance() {
}

QTransferOrder::QTransferOrder(const QTransferOrder& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void QTransferOrder::SharedCtor() {
  _cached_size_ = 0;
  orderid_ = GOOGLE_LONGLONG(0);
  ownuser_ = 0;
  touser_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

QTransferOrder::~QTransferOrder() {
  SharedDtor();
}

void QTransferOrder::SharedDtor() {
  if (this != default_instance_) {
  }
}

void QTransferOrder::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* QTransferOrder::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return QTransferOrder_descriptor_;
}

const QTransferOrder& QTransferOrder::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TransferOrder_2eproto();
  return *default_instance_;
}

QTransferOrder* QTransferOrder::default_instance_ = NULL;

QTransferOrder* QTransferOrder::New() const {
  return new QTransferOrder;
}

void QTransferOrder::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    orderid_ = GOOGLE_LONGLONG(0);
    ownuser_ = 0;
    touser_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool QTransferOrder::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 OrderID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &orderid_)));
          set_has_orderid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_OwnUser;
        break;
      }

      // required int32 OwnUser = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_OwnUser:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ownuser_)));
          set_has_ownuser();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_ToUser;
        break;
      }

      // required int32 ToUser = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_ToUser:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &touser_)));
          set_has_touser();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void QTransferOrder::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 OrderID = 1;
  if (has_orderid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->orderid(), output);
  }

  // required int32 OwnUser = 2;
  if (has_ownuser()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->ownuser(), output);
  }

  // required int32 ToUser = 3;
  if (has_touser()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->touser(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* QTransferOrder::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 OrderID = 1;
  if (has_orderid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->orderid(), target);
  }

  // required int32 OwnUser = 2;
  if (has_ownuser()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->ownuser(), target);
  }

  // required int32 ToUser = 3;
  if (has_touser()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->touser(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int QTransferOrder::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 OrderID = 1;
    if (has_orderid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->orderid());
    }

    // required int32 OwnUser = 2;
    if (has_ownuser()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->ownuser());
    }

    // required int32 ToUser = 3;
    if (has_touser()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->touser());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QTransferOrder::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const QTransferOrder* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const QTransferOrder*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void QTransferOrder::MergeFrom(const QTransferOrder& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_orderid()) {
      set_orderid(from.orderid());
    }
    if (from.has_ownuser()) {
      set_ownuser(from.ownuser());
    }
    if (from.has_touser()) {
      set_touser(from.touser());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void QTransferOrder::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void QTransferOrder::CopyFrom(const QTransferOrder& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QTransferOrder::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void QTransferOrder::Swap(QTransferOrder* other) {
  if (other != this) {
    std::swap(orderid_, other->orderid_);
    std::swap(ownuser_, other->ownuser_);
    std::swap(touser_, other->touser_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata QTransferOrder::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = QTransferOrder_descriptor_;
  metadata.reflection = QTransferOrder_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ATransferOrder::kStatsFieldNumber;
#endif  // !_MSC_VER

ATransferOrder::ATransferOrder()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ATransferOrder::InitAsDefaultInstance() {
}

ATransferOrder::ATransferOrder(const ATransferOrder& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ATransferOrder::SharedCtor() {
  _cached_size_ = 0;
  stats_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ATransferOrder::~ATransferOrder() {
  SharedDtor();
}

void ATransferOrder::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ATransferOrder::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ATransferOrder::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ATransferOrder_descriptor_;
}

const ATransferOrder& ATransferOrder::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TransferOrder_2eproto();
  return *default_instance_;
}

ATransferOrder* ATransferOrder::default_instance_ = NULL;

ATransferOrder* ATransferOrder::New() const {
  return new ATransferOrder;
}

void ATransferOrder::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    stats_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ATransferOrder::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .transMsg.EReturnStatus Stats = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::transMsg::EReturnStatus_IsValid(value)) {
            set_stats(static_cast< ::transMsg::EReturnStatus >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ATransferOrder::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .transMsg.EReturnStatus Stats = 1;
  if (has_stats()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->stats(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ATransferOrder::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .transMsg.EReturnStatus Stats = 1;
  if (has_stats()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->stats(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ATransferOrder::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .transMsg.EReturnStatus Stats = 1;
    if (has_stats()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->stats());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ATransferOrder::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ATransferOrder* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ATransferOrder*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ATransferOrder::MergeFrom(const ATransferOrder& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_stats()) {
      set_stats(from.stats());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ATransferOrder::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ATransferOrder::CopyFrom(const ATransferOrder& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ATransferOrder::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ATransferOrder::Swap(ATransferOrder* other) {
  if (other != this) {
    std::swap(stats_, other->stats_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ATransferOrder::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ATransferOrder_descriptor_;
  metadata.reflection = ATransferOrder_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace transMsg

// @@protoc_insertion_point(global_scope)
