// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UploadDesignConfig.proto

#ifndef PROTOBUF_UploadDesignConfig_2eproto__INCLUDED
#define PROTOBUF_UploadDesignConfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "EReturnStatus.pb.h"
#include "msg-GL.pb.h"
// @@protoc_insertion_point(includes)

namespace transMsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UploadDesignConfig_2eproto();
void protobuf_AssignDesc_UploadDesignConfig_2eproto();
void protobuf_ShutdownFile_UploadDesignConfig_2eproto();

class QUploadDesignConfig;
class AUploadDesignConfig;

// ===================================================================

class QUploadDesignConfig : public ::google::protobuf::Message {
 public:
  QUploadDesignConfig();
  virtual ~QUploadDesignConfig();

  QUploadDesignConfig(const QUploadDesignConfig& from);

  inline QUploadDesignConfig& operator=(const QUploadDesignConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QUploadDesignConfig& default_instance();

  void Swap(QUploadDesignConfig* other);

  // implements Message ----------------------------------------------

  QUploadDesignConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QUploadDesignConfig& from);
  void MergeFrom(const QUploadDesignConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .transMsg.GL_DesignerConfigInfo GL_DesignerConfigInfo = 1;
  inline bool has_gl_designerconfiginfo() const;
  inline void clear_gl_designerconfiginfo();
  static const int kGLDesignerConfigInfoFieldNumber = 1;
  inline const ::transMsg::GL_DesignerConfigInfo& gl_designerconfiginfo() const;
  inline ::transMsg::GL_DesignerConfigInfo* mutable_gl_designerconfiginfo();
  inline ::transMsg::GL_DesignerConfigInfo* release_gl_designerconfiginfo();
  inline void set_allocated_gl_designerconfiginfo(::transMsg::GL_DesignerConfigInfo* gl_designerconfiginfo);

  // @@protoc_insertion_point(class_scope:transMsg.QUploadDesignConfig)
 private:
  inline void set_has_gl_designerconfiginfo();
  inline void clear_has_gl_designerconfiginfo();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::transMsg::GL_DesignerConfigInfo* gl_designerconfiginfo_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_UploadDesignConfig_2eproto();
  friend void protobuf_AssignDesc_UploadDesignConfig_2eproto();
  friend void protobuf_ShutdownFile_UploadDesignConfig_2eproto();

  void InitAsDefaultInstance();
  static QUploadDesignConfig* default_instance_;
};
// -------------------------------------------------------------------

class AUploadDesignConfig : public ::google::protobuf::Message {
 public:
  AUploadDesignConfig();
  virtual ~AUploadDesignConfig();

  AUploadDesignConfig(const AUploadDesignConfig& from);

  inline AUploadDesignConfig& operator=(const AUploadDesignConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AUploadDesignConfig& default_instance();

  void Swap(AUploadDesignConfig* other);

  // implements Message ----------------------------------------------

  AUploadDesignConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AUploadDesignConfig& from);
  void MergeFrom(const AUploadDesignConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .transMsg.EReturnStatus Stats = 1;
  inline bool has_stats() const;
  inline void clear_stats();
  static const int kStatsFieldNumber = 1;
  inline ::transMsg::EReturnStatus stats() const;
  inline void set_stats(::transMsg::EReturnStatus value);

  // @@protoc_insertion_point(class_scope:transMsg.AUploadDesignConfig)
 private:
  inline void set_has_stats();
  inline void clear_has_stats();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int stats_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_UploadDesignConfig_2eproto();
  friend void protobuf_AssignDesc_UploadDesignConfig_2eproto();
  friend void protobuf_ShutdownFile_UploadDesignConfig_2eproto();

  void InitAsDefaultInstance();
  static AUploadDesignConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// QUploadDesignConfig

// required .transMsg.GL_DesignerConfigInfo GL_DesignerConfigInfo = 1;
inline bool QUploadDesignConfig::has_gl_designerconfiginfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QUploadDesignConfig::set_has_gl_designerconfiginfo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QUploadDesignConfig::clear_has_gl_designerconfiginfo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QUploadDesignConfig::clear_gl_designerconfiginfo() {
  if (gl_designerconfiginfo_ != NULL) gl_designerconfiginfo_->::transMsg::GL_DesignerConfigInfo::Clear();
  clear_has_gl_designerconfiginfo();
}
inline const ::transMsg::GL_DesignerConfigInfo& QUploadDesignConfig::gl_designerconfiginfo() const {
  return gl_designerconfiginfo_ != NULL ? *gl_designerconfiginfo_ : *default_instance_->gl_designerconfiginfo_;
}
inline ::transMsg::GL_DesignerConfigInfo* QUploadDesignConfig::mutable_gl_designerconfiginfo() {
  set_has_gl_designerconfiginfo();
  if (gl_designerconfiginfo_ == NULL) gl_designerconfiginfo_ = new ::transMsg::GL_DesignerConfigInfo;
  return gl_designerconfiginfo_;
}
inline ::transMsg::GL_DesignerConfigInfo* QUploadDesignConfig::release_gl_designerconfiginfo() {
  clear_has_gl_designerconfiginfo();
  ::transMsg::GL_DesignerConfigInfo* temp = gl_designerconfiginfo_;
  gl_designerconfiginfo_ = NULL;
  return temp;
}
inline void QUploadDesignConfig::set_allocated_gl_designerconfiginfo(::transMsg::GL_DesignerConfigInfo* gl_designerconfiginfo) {
  delete gl_designerconfiginfo_;
  gl_designerconfiginfo_ = gl_designerconfiginfo;
  if (gl_designerconfiginfo) {
    set_has_gl_designerconfiginfo();
  } else {
    clear_has_gl_designerconfiginfo();
  }
}

// -------------------------------------------------------------------

// AUploadDesignConfig

// required .transMsg.EReturnStatus Stats = 1;
inline bool AUploadDesignConfig::has_stats() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AUploadDesignConfig::set_has_stats() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AUploadDesignConfig::clear_has_stats() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AUploadDesignConfig::clear_stats() {
  stats_ = 0;
  clear_has_stats();
}
inline ::transMsg::EReturnStatus AUploadDesignConfig::stats() const {
  return static_cast< ::transMsg::EReturnStatus >(stats_);
}
inline void AUploadDesignConfig::set_stats(::transMsg::EReturnStatus value) {
  assert(::transMsg::EReturnStatus_IsValid(value));
  set_has_stats();
  stats_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace transMsg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UploadDesignConfig_2eproto__INCLUDED
